// planetData.js
const planetsData = [
  {
    id: "1",
    name: "Mercurio",
    type: "Planeta terrestre",
    diameter: "4,880 kilómetros",
    distanceFromSun: "57.9 millones de kilómetros",
    orbitalPeriod: "88 días terrestres",
    dayLength: "58.6 días terrestres",
    temperature: ["-173 °C (noche)", "427 °C (día)"],
    surfaceFeatures: ["Cráteres", "Llanuras", "Escarpas", "Rocas espaciales"],
    atmosphere: {
      composition: ["Oxígeno", "Sodio", "Hidrógeno", "Helio"],
      thickness: "Muy delgada",
      conditions: "Sin atmósfera significativa",
    },
    magneticField: "Débil y variable",
    moons: [],
    rings: [],
    missions: [
      {
        name: "Misión Mariner 10",
        year: 1974,
        purpose: "Estudio del planeta y su atmósfera",
      },
      {
        name: "Misión MESSENGER",
        year: 2004,
        purpose: "Mapeo y estudio detallado de Mercurio",
      },
    ],
    averageSurfaceTemperature: "167 °C",
    axialTilt: "0.03 grados",
    rotationDirection: "Rotación retrógrada",
    maxSurfaceTemperature: "427 °C",
    image: "https://ejemplo.com/mercurio-imagen.jpg",
  },
  {
    id: "2",
    name: "Venus",
    type: "Planeta terrestre",
    diameter: "12,104 kilómetros",
    distanceFromSun: "108.2 millones de kilómetros",
    orbitalPeriod: "225 días terrestres",
    dayLength: "116 días terrestres",
    temperature: ["462 °C"],
    surfaceFeatures: ["Volcanes", "Montañas", "Llanuras"],
    atmosphere: {
      composition: ["Dióxido de carbono", "Nitrógeno", "Ácido sulfúrico"],
      thickness: "Muy densa",
      conditions: "Efecto invernadero extremo",
    },
    magneticField: "Débil y no uniforme",
    moons: [],
    rings: [],
    missions: [
      {
        name: "Misión Magallanes",
        year: 1989,
        purpose: "Mapeo de la superficie de Venus",
      },
      {
        name: "Misión Akatsuki",
        year: 2010,
        purpose: "Estudio de la atmósfera de Venus",
      },
    ],
    averageSurfaceTemperature: "462 °C",
    axialTilt: "177.3 grados",
    rotationDirection: "Rotación retrógrada",
    maxSurfaceTemperature: "462 °C",
    image: "https://ejemplo.com/venus-imagen.jpg",
  },
  {
    id: "3",
    name: "Tierra",
    type: "Planeta terrestre",
    diameter: "12,742 kilómetros",
    distanceFromSun: "149.6 millones de kilómetros",
    orbitalPeriod: "365.25 días terrestres",
    dayLength: "24 horas",
    temperature: ["-89.2 °C a 56.7 °C"],
    surfaceFeatures: ["Montañas", "Océanos", "Desiertos"],
    atmosphere: {
      composition: ["Nitrógeno", "Oxígeno", "Argón"],
      thickness: "Moderada",
      conditions: "Adecuadas para la vida",
    },
    magneticField: "Fuerte y variable",
    moons: ["Luna"],
    rings: [],
    missions: [
      {
        name: "Misión Apollo 11",
        year: 1969,
        purpose: "Aterrizaje humano en la Luna",
      },
      {
        name: "Misión Curiosity Rover",
        year: 2012,
        purpose: "Exploración del planeta Marte",
      },
    ],
    averageSurfaceTemperature: "15 °C",
    axialTilt: "23.5 grados",
    rotationDirection: "Rotación directa",
    maxSurfaceTemperature: "56.7 °C",
    image: "https://ejemplo.com/tierra-imagen.jpg",
  },
  {
    id: "4",
    name: "Marte",
    type: "Planeta terrestre",
    diameter: "6,779 kilómetros",
    distanceFromSun: "227.9 millones de kilómetros",
    orbitalPeriod: "687 días terrestres",
    dayLength: "24.6 horas",
    temperature: ["-87 °C a -5 °C"],
    surfaceFeatures: ["Montañas", "Cañones", "Llanuras"],
    atmosphere: {
      composition: ["Dióxido de carbono", "Nitrógeno", "Argón"],
      thickness: "Delgada",
      conditions: "No apta para respirar",
    },
    magneticField: "Débil",
    moons: ["Fobos", "Deimos"],
    rings: [],
    missions: [
      {
        name: "Misión Mars Rover Curiosity",
        year: 2011,
        purpose: "Exploración de la superficie marciana",
      },
      {
        name: "Misión Mars InSight",
        year: 2018,
        purpose: "Estudio del interior de Marte",
      },
    ],
    averageSurfaceTemperature: "-55 °C",
    axialTilt: "25.2 grados",
    rotationDirection: "Rotación directa",
    maxSurfaceTemperature: "-5 °C",
    image: "https://ejemplo.com/marte-imagen.jpg",
  },
  {
    id: "5",
    name: "Júpiter",
    type: "Planeta gaseoso",
    diameter: "139,820 kilómetros",
    distanceFromSun: "778.5 millones de kilómetros",
    orbitalPeriod: "11.9 años terrestres",
    dayLength: "9.9 horas",
    temperature: ["-145 °C"],
    surfaceFeatures: ["Gran mancha roja", "Bandas atmosféricas"],
    atmosphere: {
      composition: ["Hidrógeno", "Helio", "Metano", "Ammoniaco"],
      thickness: "Muy densa",
      conditions: "No tiene una superficie sólida",
    },
    magneticField: "Fuerte",
    moons: ["Ganímedes", "Calisto", "Ío", "Europa"],
    rings: ["Anillo principal"],
    missions: [
      {
        name: "Misión Juno",
        year: 2011,
        purpose: "Estudio de la atmósfera y composición de Júpiter",
      },
      {
        name: "Misión Galileo",
        year: 1989,
        purpose: "Estudio detallado de Júpiter y sus lunas",
      },
    ],
    averageSurfaceTemperature: "-145 °C (sin superficie sólida)",
    axialTilt: "3.1 grados",
    rotationDirection: "Rotación directa",
    maxSurfaceTemperature: "-145 °C",
    image: "https://ejemplo.com/jupiter-imagen.jpg",
  },
  {
    id: "6",
    name: "Saturno",
    type: "Planeta gaseoso",
    diameter: "116,460 kilómetros",
    distanceFromSun: "1,427 millones de kilómetros",
    orbitalPeriod: "29.5 años terrestres",
    dayLength: "10.7 horas",
    temperature: ["-178 °C"],
    surfaceFeatures: ["Anillos impresionantes", "Tormentas atmosféricas"],
    atmosphere: {
      composition: ["Hidrógeno", "Helio", "Metano", "Ammoniaco"],
      thickness: "Muy densa",
      conditions: "No tiene una superficie sólida",
    },
    magneticField: "Fuerte",
    moons: ["Titán", "Encélado", "Mimas"],
    rings: ["Anillos principales", "Anillos A, B, C", "División de Cassini"],
    missions: [
      {
        name: "Misión Cassini-Huygens",
        year: 1997,
        purpose: "Estudio detallado de Saturno y sus lunas",
      },
      {
        name: "Misión Pioneer 11",
        year: 1973,
        purpose: "Estudio de la atmósfera de Saturno y sus anillos",
      },
    ],
    averageSurfaceTemperature: "-178 °C (sin superficie sólida)",
    axialTilt: "26.7 grados",
    rotationDirection: "Rotación directa",
    maxSurfaceTemperature: "-178 °C",
    image: "https://ejemplo.com/saturno-imagen.jpg",
  },
  {
    id: "7",
    name: "Urano",
    type: "Planeta gigante de hielo",
    diameter: "50,724 kilómetros",
    distanceFromSun: "2,870 millones de kilómetros",
    orbitalPeriod: "84.0 años terrestres",
    dayLength: "17.2 horas",
    temperature: ["-224 °C"],
    surfaceFeatures: ["Atmósfera turbulenta", "Anillos y lunas"],
    atmosphere: {
      composition: ["Hidrógeno", "Helio", "Metano"],
      thickness: "Moderada",
      conditions: "Sin superficie sólida",
    },
    magneticField: "Inclinado y fuerte",
    moons: ["Titania", "Oberón", "Umbriel"],
    rings: ["Anillos principales", "Anillos exteriores"],
    missions: [
      {
        name: "Misión Voyager 2",
        year: 1986,
        purpose: "Estudio detallado de Urano y sus lunas",
      },
      {
        name: "Misión Ice Giant Mission",
        purpose: "Planificación de una misión dedicada a los gigantes de hielo",
      },
    ],
    averageSurfaceTemperature: "-224 °C (sin superficie sólida)",
    axialTilt: "98 grados",
    rotationDirection: "Rotación lateral",
    maxSurfaceTemperature: "-224 °C",
    image: "https://ejemplo.com/urano-imagen.jpg",
  },
  {
    id: "8",
    name: "Neptuno",
    type: "Planeta gigante de hielo",
    diameter: "49,244 kilómetros",
    distanceFromSun: "4,498 millones de kilómetros",
    orbitalPeriod: "164.8 años terrestres",
    dayLength: "16.1 horas",
    temperature: ["-218 °C"],
    surfaceFeatures: ["Gran mancha oscura", "Vientos extremadamente rápidos"],
    atmosphere: {
      composition: ["Hidrógeno", "Helio", "Metano"],
      thickness: "Muy densa",
      conditions: "Sin superficie sólida",
    },
    magneticField: "Fuerte y desviado",
    moons: ["Tritón", "Proteo", "Nereida"],
    rings: ["Anillos principales", "Anillos incompletos"],
    missions: [
      {
        name: "Misión Voyager 2",
        year: 1989,
        purpose: "Estudio detallado de Neptuno y sus lunas",
      },
      {
        name: "Misión Neptune Orbiter",
        purpose: "Planificación de una misión orbital dedicada a Neptuno",
      },
    ],
    averageSurfaceTemperature: "-218 °C (sin superficie sólida)",
    axialTilt: "28.3 grados",
    rotationDirection: "Rotación lateral",
    maxSurfaceTemperature: "-218 °C",
    image: "https://ejemplo.com/neptuno-imagen.jpg",
  },

  // Puedes continuar agregando información para otros planetas
  // ...
];

module.exports = planetsData;
