const yogaDataPro = [
    {
      id: "1",
      name: "Adho Mukha Svanasana",
      category: "Postura de Yoga",
      benefits: [
        "Estiramiento de la columna vertebral y los músculos de la espalda",
        "Fortalecimiento de brazos, piernas y abdomen",
        "Mejora de la circulación sanguínea",
        "Alivio del estrés y la fatiga",
        "Estimulación de los órganos internos",
      ],
      steps: [
        "Comienza en posición de cuadrupedia (postura de la mesa) con las manos debajo de los hombros y las rodillas debajo de las caderas.",
        'Levanta las caderas hacia arriba mientras estiras las piernas y los brazos, formando una "V" invertida con el cuerpo.',
        "Mantén los talones bajos hacia el suelo, estira los brazos y presiona firmemente las palmas de las manos en el suelo.",
        "Relaja la cabeza y el cuello, permitiendo que el pecho se acerque a los muslos.",
        "Mantén la posición durante 30-60 segundos, respirando profundamente.",
      ],
      variations: [
        "Adho Mukha Vrksasana (parada de manos)",
        "Eka Pada Adho Mukha Svanasana (perro boca abajo con una pierna levantada)",
      ],
      tips: [
        "Alinea las muñecas debajo de los hombros y los dedos de los pies apuntando hacia adelante.",
        "Si tienes problemas en las muñecas, puedes doblar un poco las rodillas.",
        "Engancha los músculos abdominales para estabilizar la postura.",
        "Adapta la postura según tus necesidades y nivel de flexibilidad.",
      ],
    //   contraindications: [
    //     "Lesiones en las muñecas, los hombros o la espalda.",
    //     "Presión arterial alta o problemas cardíacos.",
    //     "Embarazo avanzado sin experiencia previa en yoga.",
    //   ],
    //   duration: "30-60 segundos",
    //   difficulty: "Intermedio",
    //   image: "https://ejemplo.com/adho-mukha-svanasana-imagen.jpg",
    //   video: "https://www.youtube.com/watch?v=ejemplo",
    },
    {
      id: "2",
      name: "Urdhva Mukha Svanasana",
      category: "Postura de Yoga",
      benefits: [
        "Fortalecimiento de la espalda y los glúteos",
        "Estiramiento del abdomen y los músculos del pecho",
        "Mejora de la postura y la alineación corporal",
        "Estimulación de los órganos internos",
        "Alivio de la fatiga y el estrés",
      ],
      steps: [
        "Comienza acostado boca abajo con las piernas extendidas y los dedos de los pies apoyados en el suelo.",
        "Coloca las manos a ambos lados del pecho, cerca de las costillas, con los codos doblados.",
        "Presiona las manos contra el suelo y eleva el torso, estirando los brazos y levantando el pecho hacia arriba.",
        "Mantén las piernas extendidas y los glúteos activos, elevando las piernas ligeramente del suelo.",
        "Mira hacia adelante o hacia arriba, manteniendo el cuello en una posición neutral.",
        "Mantén la postura durante 20-30 segundos, respirando profundamente.",
      ],
      variations: [
        "Bhujangasana (postura de la cobra)",
        "Salabhasana (postura de la langosta)",
      ],
      tips: [
        "Asegúrate de que los hombros estén lejos de las orejas para evitar tensión en el cuello.",
        "Engancha los músculos del abdomen para mantener la estabilidad en la postura.",
        "No fuerces la elevación del pecho; permite que sea un estiramiento cómodo.",
        "Adapta la postura según tus necesidades y limitaciones físicas.",
      ],
    //   contraindications: [
    //     "Lesiones recientes en la espalda o el cuello.",
    //     "Dolor agudo en la zona lumbar.",
    //     "Embarazo avanzado sin experiencia previa en yoga.",
    //   ],
    //   duration: "20-30 segundos",
    //   difficulty: "Intermedio",
    //   image: "https://ejemplo.com/urdhva-mukha-svanasana-imagen.jpg",
    //   video: "https://www.youtube.com/watch?v=ejemplo",
    },
    {
      id: "3",
      name: "Balasana",
      category: "Postura de Yoga",
      benefits: [
        "Estiramiento suave de la espalda y las caderas",
        "Alivio del estrés y la fatiga",
        "Mejora de la flexibilidad de la columna vertebral",
        "Relajación profunda para la mente y el cuerpo",
      ],
      steps: [
        "Comienza en posición de cuclillas con las rodillas separadas y los glúteos descansando sobre los talones.",
        "Inclina el torso hacia adelante, llevando el abdomen entre los muslos y extendiendo los brazos hacia adelante.",
        "Descansa la frente en el suelo y relaja los brazos a los lados o estíralos hacia adelante.",
        "Mantén la posición durante 1-3 minutos, respirando profundamente y relajando el cuerpo.",
      ],
      variations: [
        "Extendiendo los brazos hacia atrás y apoyando la frente en el suelo",
        "Colocando un cojín bajo la frente para mayor comodidad",
      ],
      tips: [
        "Ajusta la separación entre las rodillas según tu comodidad.",
        "Si sientes molestias en las rodillas, coloca una manta debajo de ellas.",
        "Practica la respiración consciente para aumentar la relajación.",
      ],
    //   contraindications: [
    //     "Lesiones en las rodillas o tobillos",
    //     "Dolor agudo en la espalda baja",
    //     "Embarazo avanzado sin experiencia previa en yoga",
    //   ],
    //   duration: "1-3 minutos",
    //   difficulty: "Fácil",
    //   image: "https://ejemplo.com/balasana-imagen.jpg",
    //   video: "https://www.youtube.com/watch?v=ejemplo",
    },
    {
      id: "4",
      name: "Virabhadrasana II",
      category: "Postura de Yoga",
      benefits: [
        "Fortalecimiento de piernas, brazos y abdomen",
        "Mejora de la concentración y la resistencia",
        "Estiramiento de los músculos de las piernas y la ingle",
        "Desarrollo de la estabilidad y el equilibrio",
      ],
      steps: [
        "Comienza en posición de pie con las piernas separadas.",
        "Gira el pie derecho hacia afuera 90 grados y el pie izquierdo ligeramente hacia adentro.",
        "Dobla la rodilla derecha formando un ángulo de 90 grados, asegurándote de que la rodilla esté sobre el tobillo.",
        "Extiende los brazos hacia los lados, paralelos al suelo, con la mirada fija en la mano derecha.",
        "Mantén la posición durante 30-60 segundos y repite en el lado opuesto.",
      ],
      variations: [
        "Ajustando la separación entre los pies para mayor estabilidad",
        "Colocando las manos en las caderas en lugar de extender los brazos",
      ],
      tips: [
        "Alinea el talón del pie derecho con el arco del pie izquierdo.",
        "Mantén los hombros relajados y el torso erguido.",
        "Engancha los músculos del abdomen para mayor estabilidad.",
      ],
    //   contraindications: [
    //     "Lesiones en las rodillas o caderas",
    //     "Presión arterial alta no controlada",
    //     "Dolor agudo en la espalda baja",
    //   ],
    //   duration: "30-60 segundos",
    //   difficulty: "Intermedio",
    //   image: "https://ejemplo.com/virabhadrasana-ii-imagen.jpg",
    //   video: "https://www.youtube.com/watch?v=ejemplo",
    },
    {
      id: "7",
      name: "Sirshasana",
      category: "Postura de Yoga",
      benefits: [
        "Fortalecimiento de brazos, hombros y cuello.",
        "Estimulación del sistema linfático y circulatorio.",
        "Mejora de la concentración y enfoque mental.",
        "Alivio del estrés y fatiga.",
        "Fortalecimiento de los músculos del abdomen.",
      ],
      steps: [
        "Comienza arrodillado en el suelo con las manos apoyadas en el suelo delante de ti.",
        "Coloca la parte superior de la cabeza en el suelo, formando un triángulo con las manos alrededor de la cabeza.",
        "Levanta las caderas hacia arriba y camina con los pies hacia la cabeza, manteniendo las piernas estiradas.",
        "Con cuidado, levanta una pierna y luego la otra, llevando todo el peso a la cabeza y los antebrazos.",
        "Mantén la posición durante el tiempo deseado, respirando profundamente.",
      ],
      variations: [
        "Ardha Sirshasana (postura de la cabeza a la mitad)",
        "Eka Pada Sirshasana (postura de la cabeza con una pierna levantada)",
      ],
      tips: [
        "Alinea los antebrazos y las manos de manera que formen un triángulo de apoyo estable.",
        "Evita cargar demasiado peso en la cabeza; la mayoría del peso debe estar en los antebrazos.",
        "Realiza la postura cerca de una pared para mayor seguridad, especialmente al principio.",
        "No fuerces la postura; avanza gradualmente y escucha tu cuerpo.",
      ],
    //   contraindications: [
    //     "Problemas cervicales o lesiones en la cabeza, cuello o espalda.",
    //     "Presión arterial alta o problemas cardíacos.",
    //     "Mujeres embarazadas.",
    //   ],
    //   duration: "Tiempo gradual según la práctica personal",
    //   difficulty: "Avanzado",
    //   image: "https://ejemplo.com/sirshasana-imagen.jpg",
    //   video: "https://www.youtube.com/watch?v=ejemplo",
    },
    {
      id: "8",
      name: "Dhanurasana",
      category: "Postura de Yoga",
      benefits: [
        "Estiramiento profundo de la columna vertebral.",
        "Fortalecimiento de los músculos de la espalda, glúteos y piernas.",
        "Estimulación de los órganos abdominales.",
        "Mejora de la digestión y alivio del estreñimiento.",
        "Apertura del pecho y los hombros.",
      ],
      steps: [
        "Acuéstate boca abajo con las piernas estiradas y los brazos a los lados del cuerpo.",
        "Dobla las rodillas y lleva los talones hacia los glúteos.",
        "Levanta la cabeza, el pecho y los muslos del suelo, manteniendo los brazos extendidos hacia atrás.",
        "Intenta agarrar los tobillos con las manos, creando un arco con el cuerpo.",
        "Mantén la posición durante el tiempo deseado, respirando profundamente.",
      ],
      variations: [
        "Urdhva Dhanurasana (postura de la rueda)",
        "Eka Pada Dhanurasana (postura del arco con una pierna levantada)",
      ],
      tips: [
        "No fuerces la postura; avanza gradualmente y escucha tu cuerpo.",
        "Mantén los pies paralelos en Urdhva Dhanurasana.",
        "Levanta las caderas hacia arriba para aumentar el estiramiento.",
      ],
    //   contraindications: [
    //     "Lesiones en la espalda o cuello.",
    //     "Problemas graves en los hombros o muñecas.",
    //     "Hernias o problemas abdominales.",
    //   ],
    //   duration: "30-60 segundos",
    //   difficulty: "Intermedio",
    //   image: "https://ejemplo.com/dhanurasana-imagen.jpg",
    //   video: "https://www.youtube.com/watch?v=ejemplo",
    },
    {
      id: "9",
      name: "Savasana",
      category: "Postura de Yoga",
      benefits: [
        "Relajación profunda del cuerpo y la mente.",
        "Reducción del estrés y la ansiedad.",
        "Mejora de la concentración y claridad mental.",
        "Alivio de la fatiga y el agotamiento.",
        "Equilibrio del sistema nervioso.",
      ],
      steps: [
        "Acuéstate boca arriba en el suelo con las piernas estiradas y los brazos a los lados del cuerpo.",
        "Cierra los ojos y coloca las manos con las palmas hacia arriba, dejando que los dedos se relajen.",
        "Separa ligeramente las piernas y permite que los pies caigan hacia los lados de forma natural.",
        "Relaja cada parte del cuerpo, empezando por los dedos de los pies hasta la cabeza.",
        "Mantén la respiración natural y permanece en la postura durante al menos 10-15 minutos.",
      ],
      variations: [
        "Supta Baddha Konasana (postura del zapatero reclinado)",
        "Ananda Balasana (postura feliz del bebé)",
      ],
      tips: [
        "Utiliza una manta o cojín bajo la cabeza y el cuello si es necesario.",
        "Mantén la atención en la respiración para calmar la mente.",
        "Permite que cualquier tensión o preocupación se disuelva durante la práctica.",
      ],
    //   contraindications: [
    //     "Lesiones graves en la espalda o cuello.",
    //     "Dificultades respiratorias o problemas cardíacos.",
    //     "Mujeres embarazadas deben tener precaución en las últimas etapas del embarazo.",
    //   ],
    //   duration: "10-15 minutos (o según la necesidad)",
    //   difficulty: "Fácil",
    //   image: "https://ejemplo.com/savasana-imagen.jpg",
    //   video: "https://www.youtube.com/watch?v=ejemplo",
    },
    {
      id: "10",
      name: "Paschimottanasana",
      category: "Postura de Yoga",
      benefits: [
        "Estiramiento profundo de la columna vertebral y los músculos de la espalda.",
        "Estimulación de los órganos abdominales como los riñones y el hígado.",
        "Alivio del estrés y la fatiga.",
        "Mejora de la digestión y alivio del estreñimiento.",
        "Calma la mente y ayuda en la concentración.",
      ],
      steps: [
        "Siéntate en el suelo con las piernas extendidas frente a ti.",
        "Inhala y alarga la columna vertebral.",
        "Exhala mientras te inclinas hacia adelante desde las caderas, manteniendo la espalda recta.",
        "Agarra los dedos de los pies con las manos o sostén las piernas, manteniendo los codos rectos.",
        "Mantén la postura durante 30-60 segundos, respirando profundamente.",
      ],
      variations: [
        "Urdhva Mukha Paschimottanasana (flexión hacia adelante con elevación)",
        "Parivrtta Paschimottanasana (flexión hacia adelante en torsión)",
      ],
      tips: [
        "Inhala para alargar la columna vertebral antes de la flexión hacia adelante.",
        "No fuerces la postura; avanza gradualmente según tu nivel de flexibilidad.",
        "Utiliza un cinturón o una correa alrededor de los pies si no puedes alcanzarlos con las manos.",
      ],
    //   contraindications: [
    //     "Lesiones en la espalda o las piernas.",
    //     "Problemas de disco espinal.",
    //     "Mujeres embarazadas deben practicar con precaución.",
    //   ],
    //   duration: "30-60 segundos",
    //   difficulty: "Intermedio",
    //   image: "https://ejemplo.com/paschimottanasana-imagen.jpg",
    //   video: "https://www.youtube.com/watch?v=ejemplo",
    },
    {
      id: "11",
      name: "Virabhadrasana I (Guerrero I)",
      category: "Postura de Yoga",
      benefits: [
        "Fortalecimiento de piernas, brazos y espalda.",
        "Estiramiento de los músculos del abdomen y el pecho.",
        "Mejora del equilibrio y la concentración.",
        "Estimulación de la circulación sanguínea.",
        "Desarrollo de la resistencia física y mental.",
      ],
      steps: [
        "Comienza en posición de pie con los pies juntos.",
        "Da un paso grande hacia atrás con una pierna, manteniendo la otra flexionada en un ángulo de 90 grados.",
        "Gira la cadera delantera hacia adelante y estira los brazos hacia arriba, uniéndolos sobre la cabeza.",
        "Mantén la postura durante 30-60 segundos, respirando profundamente.",
      ],
      variations: [
        "Virabhadrasana II (Guerrero II) - Extiende los brazos horizontalmente en lugar de hacia arriba.",
        "Virabhadrasana III (Guerrero III) - Eleva la pierna trasera y estira los brazos hacia adelante.",
      ],
      tips: [
        "Alinea la rodilla de la pierna delantera con el tobillo.",
        "Mantén el abdomen comprometido para fortalecer el núcleo.",
        "Fija la mirada en un punto para mejorar el equilibrio.",
      ],
    //   contraindications: [
    //     "Lesiones en la espalda, rodillas o tobillos.",
    //     "Problemas de presión arterial.",
    //     "Lesiones recientes o cirugías en la parte inferior del cuerpo.",
    //   ],
    //   duration: "30-60 segundos",
    //   difficulty: "Intermedio",
    //   image: "https://ejemplo.com/virabhadrasana-i-imagen.jpg",
    //   video: "https://www.youtube.com/watch?v=ejemplo",
    },
  ];
  module.exports = yogaDataPro;
  